import { readFileSync, writeFileSync } from "node:fs";

// Files bundled into llms-full.txt, in order. Keep in sync with the public surface.
const files = [
  "README.md",
  "CHANGELOG.md",
  "docs/API.md",
  "src/shared.ts",
  "src/client/types.ts",
  "src/client/index.ts",
  "src/component/schema.ts",
  "src/component/validators.ts",
  "src/component/validation.ts",
  "src/component/mutations.ts",
  "src/component/queries.ts",
  "src/test.ts",
];

let out = `# @vllnt/convex-progression — Full Source\n\nAuto-generated by \`pnpm generate:llms\`. Do not edit manually.\n`;

files.forEach((f) => {
  out += `\n---\n\n## ${f}\n\n`;
  out += f.endsWith(".md")
    ? readFileSync(f, "utf8")
    : "```ts\n" + readFileSync(f, "utf8") + "\n```";
  out += "\n";
});

writeFileSync("llms-full.txt", out);
console.info(`Wrote llms-full.txt (${String(files.length)} files)`);
